### ISSUE TITLE
[Request] IPv6 Link local support

### ISSUE THREAD

**Issue by romses** [OctoPrint/OctoPrint-AutoLoginConfig#3]
**Is your feature request related to a problem? Please describe.**
I am trying to configure autologin with link-local IPv6 addresses.
But adding the link-local prefix FE80::/64 is not accepted by this plugin.

**Describe the solution you'd like**
Allow FE80::/64 as a valid prefix

**Describe alternatives you've considered**
none

**Additional context**
FE80::/64 addresses are Strict Link Local and can be considered secure if the IPv4 local addresses are considered secure.

**Comment by cp2004** [comment]
Hey @romses, sorry for not getting back to this sooner, it's been a busy couple of days (see also the 1.5.0 release...). 

I'm afraid I don't know enough about IPv6 to construct some kind of validation for this, and would have to phone for help to create it (which given how busy things are, might not come). The other thing I would need to check is what exactly is supported by the underlying implementation, since this is just a frontend to a feature that [already exists in OctoPrint](https://docs.octoprint.org/en/master/configuration/config_yaml.html#access-control).

In the meantime, add an address that *is* accepted, such as `192.168.0.1/24`, and then edit it afterwards - the validation is not applied on the fields after they have been created. Potential flaw, but more effort than it was worth.

**Comment by romses** [comment]
Hey @cp2004 ,

Basically you just have to extend the regexp to accept the string FE80::/64.

**Comment by cp2004** [comment]
I have confirmation this string works in OctoPrint, will update soon.

**Comment by cp2004** [comment]
0.2.0 has been released with this feature.
